name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Use Python 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip list  # Log installed packages

    - name: Verify source directory
      run: |
        ls -l src  # Log files in src

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py --verbose

